server:
  port: 8081
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

spring:
  mvc:
    pathmatch:
      #swagger2
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:
