server:
  port: 8081



spring:
  mvc:
    pathmatch:
      #swagger2
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mariadb://localhost:3306/restest
    driver-class-name: org.mariadb.jdbc.Driver
    username: test
    password: test
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        use-sql-comments: true
        show-sql: true


logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace